{
    'name': 'HR Wellness Check',
    'version': '18.0.1.0.0',
    'summary': 'Empowering HR with Daily Wellness Insights',
    'description': 'A module for HR to track employee wellness through anonymous daily check-ins.',
    'category': 'Human Resources',
    'author': 'Odoo Community Association (OCA), Remi Toudic',
    'website': 'https://github.com/OCA/hr',
    'maintainers': ['remi-toudic'],
    'development_status': 'Beta',
    'depends': ['base', 'web', 'hr'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/wellness_data.xml',
        'wizard/hr_wellness_check_wizard_views.xml',
        'views/hr_wellness_check_views.xml',
        'views/wellness_question_views.xml',
        'views/wellness_dashboard_board.xml',
        'views/wellness_menus.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
